### PR TITLE
chore(deps): update dependencies

### PR DESCRIPTION
**Pull request by martinalbert**
`npm-check-updates` output:

```
 @rushstack/eslint-patch     ^1.1.0  →     ^1.2.0
 @types/node              ^16.11.26  →  ^18.11.18
 @vitejs/plugin-vue          ^2.2.2  →     ^4.0.0
 buttercms                   ^1.2.8  →     ^1.2.9
 eslint                      ^8.5.0  →    ^8.32.0
 eslint-plugin-vue           ^8.2.0  →     ^9.9.0
 prettier                    ^2.5.1  →     ^2.8.3
 vite                        ^2.8.4  →     ^4.0.4
 vue                        ^3.2.31  →    ^3.2.45
 vue-router                 ^4.0.12  →     ^4.1.6
 vue-tsc                    ^0.31.4  →    ^1.0.24
```

### Major changes

- mainly ending support for lower versions of node or some specific changes in api, check links for more details.
- `@types/node`
    - [v17 major changes](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V17.md#semver-major-commits)
    - [v18 major changes](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md)
- `@vitejs/plugin-vue`
    - [v3 changes](https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue-jsx%403.0.0-beta.0/packages/plugin-vue/CHANGELOG.md#300-2022-07-13)
    - [v4 changes](https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue-jsx%403.0.0-beta.0/packages/plugin-vue/CHANGELOG.md#breaking-change)
- `eslint-plugin-vue` - [v9 changes](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v9.0.0)
- `vite` - node EOL, major rollup releases, browser releases and more
    - [v3 changes](https://github.com/vitejs/vite/blob/plugin-vue%404.0.0-alpha.1/packages/vite/CHANGELOG.md#300-2022-07-13) ([migration guide](https://v3.vitejs.dev/guide/migration.html))
    - [v4 changes](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#400-2022-12-09) ([migration guide](https://vitejs.dev/guide/migration.html))
- `vue-tsc` - few breaking changes regarding `vueCompilerOptions` and extensions (more info [here](https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#100-2022107))

### `npm audit`

- on `main` branch found 2 vulnerabilities (1 moderate, 1 critical)
- after `npm audit fix` found 0
- after update of dependencies listed above found also 0

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@martinalbert does this need to be updated: https://share.getcloudapp.com/NQu4924O

**Comment by ViolanteCodes** [comment]
@martinalbert second question - i see this now runs on localhost:5173 instead of 3000. This seems like a very minor change - but there are a number of places throughout our website and materials where this starter project is already featured and instructions already exist to run on localhost:3000. Is it possible to add a configuration setting somewhere that forces this to 3000? or is that behavior not preferred for some reason?

**Comment by martinalbert** [comment]
@ViolanteCodes regarding the recommended node version, it seems like updates are about dropping support of node v12 or v14, so 16 should be still ok, unless you'll use something new from `@types/node` or `vite` which uses node v18. I would have to dig deeper to check if everything that you use is compatible with v16.

Regarding the port, you're right, I can change the port to 3000.

**Review by ViolanteCodes — APPROVED** [review]
This LGTM - both localhost and preview app seem to be performing properly

**Pull request merged**
